language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "Services"
    token:
      secure: ed2fc5ef528e0f21afe02f01ecc5eb83a4512d75
jobs:
  include:
    - stage: Build
      script: npm run build
    - stage: Unit Test
      script: npm run test a
    - stage: Sonar Qube
      script: sonar-scanner